### ISSUE TITLE
Theme doesn't work with a Melodrama generated presentation

### ISSUE THREAD

**Issue by shreyasbharath** [sebald/spectacle-theme-nova#7]
All I did was change the below line in the generated presentation

```
import createTheme from 'spectacle/lib/themes/default';
```
to
```
import createTheme from 'spectacle-theme-nova';
```

Here's the error from my browser console

![image](https://user-images.githubusercontent.com/1886010/26852682-2a31c2d6-4b63-11e7-83e1-5e597ded80c5.png)

**Comment by sebald** [comment]
Please update your `melodrama-scripts` to `2.1.0`. Should be fixed 🙃

**Comment by sebald** [comment]
J4I `spectacle-theme-nova/bundle` still worked.

The reason why this theme didn't work with `melodrama` anymore was due to the fact that most of the `node_modules` is excluded since `2.0.0`. This improved speed and solves an issue with `babel-standalone` that is included in `spectacle` since `2.0.0.`.

**Comment by shreyasbharath** [comment]
`spectacle-theme-nova/bundle` worked as you mentioned.

I just tried `spectacle-theme-nova` with 2.1.0 and it still throws an error as below.

![console](https://user-images.githubusercontent.com/1886010/26902874-fadcc770-4c2e-11e7-8ad3-8a89c7c3cf6d.png)

**Comment by sebald** [comment]
Can you please provide steps to reproduce? I just created a new presentation with `melodrama` + `spectacle-theme-nova` without any issues. Only thing I changed:

```diff
- import createTheme from 'spectacle/lib/themes/default';
+ import createTheme from 'spectacle-theme-nova';
```

```json
{
  "name": "presentation-example",
  "version": "1.0.0",
  "private": true,
  "devDependencies": {
    "melodrama-scripts": "2.1.0"
  },
  "readme": "README.md",
  "scripts": {
    "start": "melodrama-scripts start index.js",
    "build": "melodrama-scripts build index.js"
  },
  "dependencies": {
    "prismjs": "1.6.0",
    "react": "15.5.4",
    "react-dom": "15.5.4",
    "spectacle": "2.1.0",
    "spectacle-theme-nova": "1.3.0"
  }
}
```

Are you importing other libs?
